server:
  port: 8084

spring:
  application:
    name: WellnessHub-Backend

  datasource:
    driver-class-name: org.postgresql.Driver
    #jdbc:postgresql://dpg-d3p8p3t6ubrc73evnidg-a.oregon-postgres.render.com:5432/wellnesshubdb
    url: jdbc:postgresql://localhost:5432/wellnesshubDB
    username: wellnesshubdb_user
    password: I6uWqfiX7YCtCUSVTq1zDH3095yURnEs

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: malekeljendoubi@gmail.com
    password: uroc fosm vsez xfuo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        transport:
          protocol: smtp

app:
  frontend:
    url: https://wellnesshub.com.tn/

# Configuration JWT
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 3600000  # 1 heure en millisecondes
  refresh-token:
    expiration: 604800000  # 7 jours en millisecondes

# Configuration SpringDoc/Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Configuration des logs
logging:
  level:
    com.example: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
